spring:
  datasource:
    url: ${PROD_DATABASE_URL}
    username: ${PROD_DATABASE_USERNAME}
    password: ${PROD_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

logging:
  level:
    org.hibernate.SQL: WARN
    backend: INFO
